version: '3.5'

services:
  mongodb:
    container_name: groomie-mongo
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - groomie-network
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongodb:/data/db
    restart: unless-stopped

  mongo-express:
    container_name: groomie-mongo-express
    image: mongo-express:0.54
    depends_on:
      - mongodb
    networks:
      - groomie-network
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    restart: unless-stopped

networks:
  groomie-network:
    driver: bridge

volumes:
  mongodb: